CREATE OR REPLACE VIEW pg_compat.routines AS
SELECT ''::VARCHAR AS specific_catalog, ''::VARCHAR AS specific_schema, ''::VARCHAR AS specific_name,
       ''::VARCHAR AS routine_catalog, ''::VARCHAR AS routine_schema, ''::VARCHAR AS routine_name,
       ''::VARCHAR AS routine_type, NULL::VARCHAR AS module_catalog, NULL::VARCHAR AS module_schema,
       NULL::VARCHAR AS module_name, NULL::VARCHAR AS dtd_identifier, 'SQL'::VARCHAR AS routine_body,
       NULL::VARCHAR AS routine_definition, NULL::VARCHAR AS external_name,
       'SQL'::VARCHAR AS external_language, 'GENERAL'::VARCHAR AS parameter_style,
       'YES'::VARCHAR AS is_deterministic, 'MODIFIES'::VARCHAR AS sql_data_access,
       NULL::VARCHAR AS sql_path, 'NO'::VARCHAR AS schema_level_routine,
       0::INTEGER AS max_dynamic_result_sets, NULL::VARCHAR AS created, NULL::VARCHAR AS last_altered,
       NULL::VARCHAR AS new_savepoint_level, NULL::VARCHAR AS is_new_savepoint_level,
       NULL::VARCHAR AS is_unsaved_savepoint_level, 'DEFINER'::VARCHAR AS security_type,
       'NO'::VARCHAR AS sql_data_access_path, 'NO'::VARCHAR AS result_cast_from_data_type,
       NULL::VARCHAR AS result_cast_as_locators, NULL::VARCHAR AS result_cast_char_maximum_length,
       NULL::VARCHAR AS result_cast_char_octet_length, NULL::VARCHAR AS result_cast_char_set_catalog,
       NULL::VARCHAR AS result_cast_char_set_schema, NULL::VARCHAR AS result_cast_char_set_name,
       NULL::VARCHAR AS result_cast_collation_catalog, NULL::VARCHAR AS result_cast_collation_schema,
       NULL::VARCHAR AS result_cast_collation_name, NULL::VARCHAR AS result_cast_numeric_precision,
       NULL::VARCHAR AS result_cast_numeric_precision_radix, NULL::VARCHAR AS result_cast_numeric_scale,
       NULL::VARCHAR AS result_cast_datetime_precision, NULL::VARCHAR AS result_cast_interval_type,
       NULL::VARCHAR AS result_cast_interval_precision, NULL::VARCHAR AS result_cast_scope_catalog,
       NULL::VARCHAR AS result_cast_scope_schema, NULL::VARCHAR AS result_cast_scope_name,
       NULL::VARCHAR AS result_cast_maximum_cardinality, NULL::VARCHAR AS result_cast_dtd_identifier LIMIT 0
;
